# Generated by Django 4.0.3 on 2022-03-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('infosec_issue', 'Information Security issue'), ('software_problem', 'Software problem'), ('hardware_problem', 'Hardware problem'), ('network_issue', 'Networking issue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('in_progress', 'In progress')], max_length=20),
        ),
    ]
